defaults:
  - visualization: eval

num_workers: 0
batch_size: 1
cuda: 0
weight_name: "miou" # Used during resume, select with model to load from [miou, macc, acc..., latest]
enable_cudnn: True
checkpoint_dir: "/mnt/Work/OneDrive_backup_data/OpenEDS2021_EyeSeg3D/outputs/benchmark/benchmark-KPDeformableConvPaper-20210726_150206" # "/mnt/XProject/OpenEDS2021_EyeSeg3D/outputs/2021-07-26/14-15-06"   # "{your_path}/outputs/2020-01-28/11-04-13" for example
model_name: KPDeformableConvPaper #KPConvPaper # KPConvPaper
precompute_multi_scale: True # Compute multiscate features on cpu for faster training / inference
enable_dropout: False
voting_runs: 1
shuffle: False
debugging: default

tracker_options: # Extra options for the tracker
  full_res: False
  make_submission: True

hydra:
  run:
    dir: ${checkpoint_dir}/eval/${now:%Y-%m-%d_%H-%M-%S}

pretty_print: False

